//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteList.ETOResults.QaaWS.Samples.Sites {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Sites", ConfigurationName="ETOResults.QaaWS.Samples.Sites.QueryAsAServiceSoap")]
    public interface QueryAsAServiceSoap {
        
        // CODEGEN: Generating message contract since the operation runQueryAsAService is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Sites/runQueryAsAService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SiteList.ETOResults.QaaWS.Samples.Sites.runQueryAsAServiceResponse runQueryAsAService(SiteList.ETOResults.QaaWS.Samples.Sites.runQueryAsAServiceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Sites")]
    public partial class QaaWSHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIDField;
        
        private string serializedSessionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string sessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("sessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string serializedSession {
            get {
                return this.serializedSessionField;
            }
            set {
                this.serializedSessionField = value;
                this.RaisePropertyChanged("serializedSession");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Sites")]
    public partial class Row : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string site_NameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Site_Name {
            get {
                return this.site_NameField;
            }
            set {
                this.site_NameField = value;
                this.RaisePropertyChanged("Site_Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Sites")]
    public partial class runQueryAsAService : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class runQueryAsAServiceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="Sites")]
        public SiteList.ETOResults.QaaWS.Samples.Sites.QaaWSHeader QaaWSHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Sites", Order=0)]
        public SiteList.ETOResults.QaaWS.Samples.Sites.runQueryAsAService runQueryAsAService;
        
        public runQueryAsAServiceRequest() {
        }
        
        public runQueryAsAServiceRequest(SiteList.ETOResults.QaaWS.Samples.Sites.QaaWSHeader QaaWSHeader, SiteList.ETOResults.QaaWS.Samples.Sites.runQueryAsAService runQueryAsAService) {
            this.QaaWSHeader = QaaWSHeader;
            this.runQueryAsAService = runQueryAsAService;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="runQueryAsAServiceResponse", WrapperNamespace="Sites", IsWrapped=true)]
    public partial class runQueryAsAServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Sites", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("row", IsNullable=false)]
        public Row[] table;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Sites", Order=1)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Sites", Order=2)]
        public string creatorname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Sites", Order=3)]
        public System.DateTime creationdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Sites", Order=4)]
        public string creationdateformated;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Sites", Order=5)]
        public string description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Sites", Order=6)]
        public string universe;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Sites", Order=7)]
        public int queryruntime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Sites", Order=8)]
        public int fetchedrows;
        
        public runQueryAsAServiceResponse() {
        }
        
        public runQueryAsAServiceResponse(Row[] table, string message, string creatorname, System.DateTime creationdate, string creationdateformated, string description, string universe, int queryruntime, int fetchedrows) {
            this.table = table;
            this.message = message;
            this.creatorname = creatorname;
            this.creationdate = creationdate;
            this.creationdateformated = creationdateformated;
            this.description = description;
            this.universe = universe;
            this.queryruntime = queryruntime;
            this.fetchedrows = fetchedrows;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryAsAServiceSoapChannel : SiteList.ETOResults.QaaWS.Samples.Sites.QueryAsAServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryAsAServiceSoapClient : System.ServiceModel.ClientBase<SiteList.ETOResults.QaaWS.Samples.Sites.QueryAsAServiceSoap>, SiteList.ETOResults.QaaWS.Samples.Sites.QueryAsAServiceSoap {
        
        public QueryAsAServiceSoapClient() {
        }
        
        public QueryAsAServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryAsAServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryAsAServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryAsAServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiteList.ETOResults.QaaWS.Samples.Sites.runQueryAsAServiceResponse SiteList.ETOResults.QaaWS.Samples.Sites.QueryAsAServiceSoap.runQueryAsAService(SiteList.ETOResults.QaaWS.Samples.Sites.runQueryAsAServiceRequest request) {
            return base.Channel.runQueryAsAService(request);
        }
        
        public Row[] runQueryAsAService(SiteList.ETOResults.QaaWS.Samples.Sites.QaaWSHeader QaaWSHeader, SiteList.ETOResults.QaaWS.Samples.Sites.runQueryAsAService runQueryAsAService1, out string message, out string creatorname, out System.DateTime creationdate, out string creationdateformated, out string description, out string universe, out int queryruntime, out int fetchedrows) {
            SiteList.ETOResults.QaaWS.Samples.Sites.runQueryAsAServiceRequest inValue = new SiteList.ETOResults.QaaWS.Samples.Sites.runQueryAsAServiceRequest();
            inValue.QaaWSHeader = QaaWSHeader;
            inValue.runQueryAsAService = runQueryAsAService1;
            SiteList.ETOResults.QaaWS.Samples.Sites.runQueryAsAServiceResponse retVal = ((SiteList.ETOResults.QaaWS.Samples.Sites.QueryAsAServiceSoap)(this)).runQueryAsAService(inValue);
            message = retVal.message;
            creatorname = retVal.creatorname;
            creationdate = retVal.creationdate;
            creationdateformated = retVal.creationdateformated;
            description = retVal.description;
            universe = retVal.universe;
            queryruntime = retVal.queryruntime;
            fetchedrows = retVal.fetchedrows;
            return retVal.table;
        }
    }
}
