//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParticipantList.ETOResults.QaaWS.Samples.Participants {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Participants", ConfigurationName="ETOResults.QaaWS.Samples.Participants.QueryAsAServiceSoap")]
    public interface QueryAsAServiceSoap {
        
        // CODEGEN: Generating message contract since the operation runQueryAsAService is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Participants/runQueryAsAService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAServiceResponse runQueryAsAService(ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAServiceRequest request);
        
        // CODEGEN: Generating message contract since the operation runQueryAsAServiceEx is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Participants/runQueryAsAServiceEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAServiceExResponse runQueryAsAServiceEx(ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAServiceExRequest request);
        
        // CODEGEN: Generating message contract since the operation valuesOf_Site_Name is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Participants/valuesOf_Site_Name", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ParticipantList.ETOResults.QaaWS.Samples.Participants.valuesOf_Site_NameResponse valuesOf_Site_Name(ParticipantList.ETOResults.QaaWS.Samples.Participants.valuesOf_Site_NameRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Participants")]
    public partial class QaaWSHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIDField;
        
        private string serializedSessionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string sessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("sessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string serializedSession {
            get {
                return this.serializedSessionField;
            }
            set {
                this.serializedSessionField = value;
                this.RaisePropertyChanged("serializedSession");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Participants")]
    public partial class LovValueIndex : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        private string indexField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
                this.RaisePropertyChanged("index");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Participants")]
    public partial class Row : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<double> participant_Site_IdentifierField;
        
        private string nameField;
        
        private string case_NumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<double> Participant_Site_Identifier {
            get {
                return this.participant_Site_IdentifierField;
            }
            set {
                this.participant_Site_IdentifierField = value;
                this.RaisePropertyChanged("Participant_Site_Identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Case_Number {
            get {
                return this.case_NumberField;
            }
            set {
                this.case_NumberField = value;
                this.RaisePropertyChanged("Case_Number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Participants")]
    public partial class runQueryAsAService : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string passwordField;
        
        private string siteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
                this.RaisePropertyChanged("Site");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class runQueryAsAServiceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="Participants")]
        public ParticipantList.ETOResults.QaaWS.Samples.Participants.QaaWSHeader QaaWSHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=0)]
        public ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAService runQueryAsAService;
        
        public runQueryAsAServiceRequest() {
        }
        
        public runQueryAsAServiceRequest(ParticipantList.ETOResults.QaaWS.Samples.Participants.QaaWSHeader QaaWSHeader, ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAService runQueryAsAService) {
            this.QaaWSHeader = QaaWSHeader;
            this.runQueryAsAService = runQueryAsAService;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="runQueryAsAServiceResponse", WrapperNamespace="Participants", IsWrapped=true)]
    public partial class runQueryAsAServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("row", IsNullable=false)]
        public Row[] table;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=1)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=2)]
        public string creatorname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=3)]
        public System.DateTime creationdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=4)]
        public string creationdateformated;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=5)]
        public string description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=6)]
        public string universe;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=7)]
        public int queryruntime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=8)]
        public int fetchedrows;
        
        public runQueryAsAServiceResponse() {
        }
        
        public runQueryAsAServiceResponse(Row[] table, string message, string creatorname, System.DateTime creationdate, string creationdateformated, string description, string universe, int queryruntime, int fetchedrows) {
            this.table = table;
            this.message = message;
            this.creatorname = creatorname;
            this.creationdate = creationdate;
            this.creationdateformated = creationdateformated;
            this.description = description;
            this.universe = universe;
            this.queryruntime = queryruntime;
            this.fetchedrows = fetchedrows;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Participants")]
    public partial class runQueryAsAServiceEx : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string passwordField;
        
        private LovValueIndex siteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public LovValueIndex Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
                this.RaisePropertyChanged("Site");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class runQueryAsAServiceExRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="Participants")]
        public ParticipantList.ETOResults.QaaWS.Samples.Participants.QaaWSHeader QaaWSHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=0)]
        public ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAServiceEx runQueryAsAServiceEx;
        
        public runQueryAsAServiceExRequest() {
        }
        
        public runQueryAsAServiceExRequest(ParticipantList.ETOResults.QaaWS.Samples.Participants.QaaWSHeader QaaWSHeader, ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAServiceEx runQueryAsAServiceEx) {
            this.QaaWSHeader = QaaWSHeader;
            this.runQueryAsAServiceEx = runQueryAsAServiceEx;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="runQueryAsAServiceExResponse", WrapperNamespace="Participants", IsWrapped=true)]
    public partial class runQueryAsAServiceExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("row", IsNullable=false)]
        public Row[] table;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=1)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=2)]
        public string creatorname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=3)]
        public System.DateTime creationdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=4)]
        public string creationdateformated;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=5)]
        public string description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=6)]
        public string universe;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=7)]
        public int queryruntime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=8)]
        public int fetchedrows;
        
        public runQueryAsAServiceExResponse() {
        }
        
        public runQueryAsAServiceExResponse(Row[] table, string message, string creatorname, System.DateTime creationdate, string creationdateformated, string description, string universe, int queryruntime, int fetchedrows) {
            this.table = table;
            this.message = message;
            this.creatorname = creatorname;
            this.creationdate = creationdate;
            this.creationdateformated = creationdateformated;
            this.description = description;
            this.universe = universe;
            this.queryruntime = queryruntime;
            this.fetchedrows = fetchedrows;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Participants")]
    public partial class valuesOf_Site_Name : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string passwordField;
        
        private string searchLovField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string searchLov {
            get {
                return this.searchLovField;
            }
            set {
                this.searchLovField = value;
                this.RaisePropertyChanged("searchLov");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class valuesOf_Site_NameRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="Participants")]
        public ParticipantList.ETOResults.QaaWS.Samples.Participants.QaaWSHeader QaaWSHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=0)]
        public ParticipantList.ETOResults.QaaWS.Samples.Participants.valuesOf_Site_Name valuesOf_Site_Name;
        
        public valuesOf_Site_NameRequest() {
        }
        
        public valuesOf_Site_NameRequest(ParticipantList.ETOResults.QaaWS.Samples.Participants.QaaWSHeader QaaWSHeader, ParticipantList.ETOResults.QaaWS.Samples.Participants.valuesOf_Site_Name valuesOf_Site_Name) {
            this.QaaWSHeader = QaaWSHeader;
            this.valuesOf_Site_Name = valuesOf_Site_Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="valuesOf_Site_NameResponse", WrapperNamespace="Participants", IsWrapped=true)]
    public partial class valuesOf_Site_NameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("valueindex", IsNullable=false)]
        public LovValueIndex[] lov;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=1)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=2)]
        public bool delegated;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Participants", Order=3)]
        public bool partialResult;
        
        public valuesOf_Site_NameResponse() {
        }
        
        public valuesOf_Site_NameResponse(LovValueIndex[] lov, string message, bool delegated, bool partialResult) {
            this.lov = lov;
            this.message = message;
            this.delegated = delegated;
            this.partialResult = partialResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryAsAServiceSoapChannel : ParticipantList.ETOResults.QaaWS.Samples.Participants.QueryAsAServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryAsAServiceSoapClient : System.ServiceModel.ClientBase<ParticipantList.ETOResults.QaaWS.Samples.Participants.QueryAsAServiceSoap>, ParticipantList.ETOResults.QaaWS.Samples.Participants.QueryAsAServiceSoap {
        
        public QueryAsAServiceSoapClient() {
        }
        
        public QueryAsAServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryAsAServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryAsAServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryAsAServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAServiceResponse ParticipantList.ETOResults.QaaWS.Samples.Participants.QueryAsAServiceSoap.runQueryAsAService(ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAServiceRequest request) {
            return base.Channel.runQueryAsAService(request);
        }
        
        public Row[] runQueryAsAService(ParticipantList.ETOResults.QaaWS.Samples.Participants.QaaWSHeader QaaWSHeader, ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAService runQueryAsAService1, out string message, out string creatorname, out System.DateTime creationdate, out string creationdateformated, out string description, out string universe, out int queryruntime, out int fetchedrows) {
            ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAServiceRequest inValue = new ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAServiceRequest();
            inValue.QaaWSHeader = QaaWSHeader;
            inValue.runQueryAsAService = runQueryAsAService1;
            ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAServiceResponse retVal = ((ParticipantList.ETOResults.QaaWS.Samples.Participants.QueryAsAServiceSoap)(this)).runQueryAsAService(inValue);
            message = retVal.message;
            creatorname = retVal.creatorname;
            creationdate = retVal.creationdate;
            creationdateformated = retVal.creationdateformated;
            description = retVal.description;
            universe = retVal.universe;
            queryruntime = retVal.queryruntime;
            fetchedrows = retVal.fetchedrows;
            return retVal.table;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAServiceExResponse ParticipantList.ETOResults.QaaWS.Samples.Participants.QueryAsAServiceSoap.runQueryAsAServiceEx(ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAServiceExRequest request) {
            return base.Channel.runQueryAsAServiceEx(request);
        }
        
        public Row[] runQueryAsAServiceEx(ParticipantList.ETOResults.QaaWS.Samples.Participants.QaaWSHeader QaaWSHeader, ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAServiceEx runQueryAsAServiceEx1, out string message, out string creatorname, out System.DateTime creationdate, out string creationdateformated, out string description, out string universe, out int queryruntime, out int fetchedrows) {
            ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAServiceExRequest inValue = new ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAServiceExRequest();
            inValue.QaaWSHeader = QaaWSHeader;
            inValue.runQueryAsAServiceEx = runQueryAsAServiceEx1;
            ParticipantList.ETOResults.QaaWS.Samples.Participants.runQueryAsAServiceExResponse retVal = ((ParticipantList.ETOResults.QaaWS.Samples.Participants.QueryAsAServiceSoap)(this)).runQueryAsAServiceEx(inValue);
            message = retVal.message;
            creatorname = retVal.creatorname;
            creationdate = retVal.creationdate;
            creationdateformated = retVal.creationdateformated;
            description = retVal.description;
            universe = retVal.universe;
            queryruntime = retVal.queryruntime;
            fetchedrows = retVal.fetchedrows;
            return retVal.table;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ParticipantList.ETOResults.QaaWS.Samples.Participants.valuesOf_Site_NameResponse ParticipantList.ETOResults.QaaWS.Samples.Participants.QueryAsAServiceSoap.valuesOf_Site_Name(ParticipantList.ETOResults.QaaWS.Samples.Participants.valuesOf_Site_NameRequest request) {
            return base.Channel.valuesOf_Site_Name(request);
        }
        
        public LovValueIndex[] valuesOf_Site_Name(ParticipantList.ETOResults.QaaWS.Samples.Participants.QaaWSHeader QaaWSHeader, ParticipantList.ETOResults.QaaWS.Samples.Participants.valuesOf_Site_Name valuesOf_Site_Name1, out string message, out bool delegated, out bool partialResult) {
            ParticipantList.ETOResults.QaaWS.Samples.Participants.valuesOf_Site_NameRequest inValue = new ParticipantList.ETOResults.QaaWS.Samples.Participants.valuesOf_Site_NameRequest();
            inValue.QaaWSHeader = QaaWSHeader;
            inValue.valuesOf_Site_Name = valuesOf_Site_Name1;
            ParticipantList.ETOResults.QaaWS.Samples.Participants.valuesOf_Site_NameResponse retVal = ((ParticipantList.ETOResults.QaaWS.Samples.Participants.QueryAsAServiceSoap)(this)).valuesOf_Site_Name(inValue);
            message = retVal.message;
            delegated = retVal.delegated;
            partialResult = retVal.partialResult;
            return retVal.lov;
        }
    }
}
